from __future__ import annotations

from app.models.source import SourceDefinition


def get_default_sources() -> list[SourceDefinition]:
    return [
        SourceDefinition(
            slug="carrefour-reunion-catalogues",
            name="Carrefour Reunion catalogues",
            content_family="shopping",
            source_type="html",
            source_url="https://www.carrefour-reunion.com/catalogues/carrefour",
            official_domain="carrefour-reunion.com",
            parser_key="carrefour_reunion",
            scope_type="island",
            retailer_slug="carrefour-reunion",
        ),
        SourceDefinition(
            slug="magasins-u-reunion-home",
            name="Magasins U Reunion",
            content_family="shopping",
            source_type="html",
            source_url="https://www.magasins-u.re/",
            official_domain="magasins-u.re",
            parser_key="magasins_u_reunion",
            scope_type="island",
            retailer_slug="magasins-u-reunion",
        ),
        SourceDefinition(
            slug="run-market-reunion-home",
            name="Run Market Reunion",
            content_family="shopping",
            source_type="html",
            source_url="https://www.run-market.re/",
            official_domain="run-market.re",
            parser_key="run_market_reunion",
            scope_type="island",
            retailer_slug="run-market-reunion",
        ),
        SourceDefinition(
            slug="auchan-saint-louis-catalogues",
            name="Auchan Saint-Louis catalogues",
            content_family="shopping",
            source_type="html",
            source_url="https://www.auchansaintlouis.com/les-catalogues",
            official_domain="auchansaintlouis.com",
            parser_key="auchan_saint_louis",
            scope_type="commune",
            retailer_slug="auchan-saint-louis",
            commune="Saint-Louis",
        ),
        SourceDefinition(
            slug="e-leclerc-reunion-catalogues",
            name="E.Leclerc Reunion catalogues",
            content_family="shopping",
            source_type="html",
            source_url="https://www.e-leclerc.re/index.php/page/catalogues-reunion",
            official_domain="e-leclerc.re",
            parser_key="eleclerc_reunion",
            scope_type="island",
            retailer_slug="eleclerc-reunion",
            is_active=True,
            metadata={"activation_status": "validated_for_global_dry_run"},
        ),
        SourceDefinition(
            slug="mairie-saint-paul-events",
            name="Mairie Saint-Paul events",
            content_family="event",
            source_type="html",
            source_url="https://www.mairie-saintpaul.re/",
            official_domain="mairie-saintpaul.re",
            parser_key="saint_paul_events",
            scope_type="commune",
            organizer_name="Ville de Saint-Paul",
            commune="Saint-Paul",
        ),
        SourceDefinition(
            slug="ville-port-permanent-leisure",
            name="Ville du Port family leisure",
            content_family="permanent_leisure",
            source_type="html",
            source_url="https://www.ville-port.re/horaires-douverture-de-la-piscine-et-des-jeux-deau/",
            official_domain="ville-port.re",
            parser_key="ville_port_permanent_leisure",
            scope_type="commune",
            organizer_name="Ville du Port",
            commune="Le Port",
        ),
    ]
