import {
  BadgePercent,
  BarChart3,
  Bot,
  CalendarClock,
  Car,
  CheckCircle2,
  ClipboardList,
  FileCheck2,
  Hammer,
  Home,
  Landmark,
  Lightbulb,
  ListChecks,
  Mail,
  MapPin,
  Menu,
  Moon,
  PartyPopper,
  PiggyBank,
  Plus,
  ReceiptText,
  ScanLine,
  Settings2,
  ShoppingBasket,
  Sparkles,
  Store,
  Sun,
  Trophy,
  User,
  Utensils,
  Wallet,
} from "lucide-react"

export const BkIcons = {
  add: Plus,
  aides: Landmark,
  alert: Lightbulb,
  appearance: Settings2,
  assistant: Bot,
  budget: Wallet,
  calendar: CalendarClock,
  check: CheckCircle2,
  contact: Mail,
  dashboard: Home,
  deals: BadgePercent,
  depenses: BarChart3,
  demarches: FileCheck2,
  dark: Moon,
  food: Utensils,
  homeServices: Hammer,
  leisure: PartyPopper,
  light: Sun,
  list: ListChecks,
  location: MapPin,
  menu: Menu,
  premium: Sparkles,
  receipts: ReceiptText,
  rewards: Trophy,
  savings: PiggyBank,
  scan: ScanLine,
  shopping: ShoppingBasket,
  stats: BarChart3,
  store: Store,
  transport: Car,
  user: User,
  abonnements: ClipboardList,
}
